sudo: required
language: php
cache:
  directories:
    - $HOME/.cache/composer/files
    - $HOME/.composer/cache/files
php:
  - '7.2'
before_install:

install:
  - 'travis_retry composer install --no-interaction'
services:

before_script:
  - 'export DISPLAY=:99.0'
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24"
  - './vendor/laravel/dusk/bin/chromedriver-linux &'
  - 'php artisan serve &'

